USE [sbeap-app1]
GO

-- Update staff attending conferences with names.
update SBEAPCONFERENCELOG
set STRSTAFFATTENDING = null
where STRSTAFFATTENDING in (',', '');

update SBEAPCONFERENCELOG
set STRSTAFFATTENDING = replace(STRSTAFFATTENDING, ',', ', ');

update SBEAPCONFERENCELOG
set STRSTAFFATTENDING = replace(STRSTAFFATTENDING, '116', 'Vicky Giles');

update SBEAPCONFERENCELOG
set STRSTAFFATTENDING = replace(STRSTAFFATTENDING, '169', 'Jeff Carter');

update SBEAPCONFERENCELOG
set STRSTAFFATTENDING = replace(STRSTAFFATTENDING, '270', 'Teresa Shiflett');

update SBEAPCONFERENCELOG
set STRSTAFFATTENDING = replace(STRSTAFFATTENDING, '276', 'Chip Scroggs');

update SBEAPCONFERENCELOG
set STRSTAFFATTENDING = replace(STRSTAFFATTENDING, '277', 'Ann Manigault');

update SBEAPCONFERENCELOG
set STRSTAFFATTENDING = replace(STRSTAFFATTENDING, '281', 'Rachel Cochran');

update SBEAPCONFERENCELOG
set STRSTAFFATTENDING = replace(STRSTAFFATTENDING, '321', 'John Yntema');

update SBEAPCONFERENCELOG
set STRSTAFFATTENDING = replace(STRSTAFFATTENDING, '388', 'Vanetra Garrett');

update SBEAPCONFERENCELOG
set STRSTAFFATTENDING = replace(STRSTAFFATTENDING, '391', 'Leslie Churilla');

update SBEAPCONFERENCELOG
set STRSTAFFATTENDING = replace(STRSTAFFATTENDING, '472', 'Mary Talukder');
