name: Lighthouse Check

on:
  pull_request:

jobs:
  lighthouse-analysis:
    # ↓ Change this to "false" to disable the workflow without any alert messages.
    if: ${{ true }}
    # ↑ Change to "true" (or delete) to enable the workflow.

    name: Analyze with Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Set up Node.js (npm)
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: dotnet build

      - name: Run Web Server in the background
        run: |
          cd src/WebApp
          dotnet run --no-build &

      - name: Create temporary folder for artifacts storage
        run: mkdir /tmp/lighthouse-artifacts

      - name: Install Lighthouse through NPM
        run: |
          npm install -g @foo-software/lighthouse-check@7.0.0

      - name: Run Lighthouse Check
        run: |
          lighthouse-check \
          --verbose \
          --prCommentEnabled \
          --emulatedFormFactor "all" \
          --prCommentAccessToken "${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}" \
          --prCommentUrl "https://api.github.com/repos/gaepdit/template-app/pulls/$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')/reviews" \
          --timeout "5" \
          --overridesJsonFile ".github/workflows/lighthouse-config.json" \
          --urls "https://localhost:7229" \
          --outputDirectory /tmp/lighthouse-artifacts

      - name: Handle Lighthouse Check results
        run: |
          lighthouse-check-status --outputDirectory /tmp/lighthouse-artifacts \
          --minAccessibilityScore 40 \
          --minBestPracticesScore 40 \
          --minPerformanceScore 40 \
          --minSeoScore 40
